name: DoomsdayEssentials
main: top.mrxiaom.doomsdayessentials.Main
version: 2.5
api-version: 1.15
author: DoomsdaySociety
depend: 
- AdvancedAchievements
- AdvancedBan
- AmazingBot
- AuthMe
- Citizens
- CommandPrompter
- Companions
- CoreProtect
- Graves
- Marriage
- mcMMO
- Mcrmb
- Multiverse-Core
- MyPet
- NBTAPI
- PlaceholderAPI
- PlayerPoints
- PlotSquared
- PluginUpdater
- ProtocolLib
- QuickShop
- Residence
- RPGItems
- ServerMarket
- Shopkeepers
- Vault
- WorldEdit